spring:
  application:
    name: nocodeapp
server:
  port: 8123
  servlet:
    context-path: /api
# springdoc-openapi项目配置
springdoc:
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.ai.nocodeapp.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn